# Generated by Django 5.2.7 on 2025-10-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0002_remove_company_company_id_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='id',
        ),
        migrations.AddField(
            model_name='company',
            name='company_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
