# Generated by Django 5.2.7 on 2025-10-24 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0003_remove_company_id_company_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sender',
            name='user_id',
        ),
        migrations.AddField(
            model_name='sender',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
