# Generated by Django 5.2.7 on 2025-10-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0004_remove_sender_user_id_sender_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='variable_type',
            field=models.CharField(choices=[('enable', 'Enable'), ('disable', 'Disable')], default='enable', max_length=10),
        ),
    ]
