# Generated by Django 5.2.7 on 2025-10-27 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0006_alter_messagetemplate_variable_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composemessageline',
            name='sms_id',
        ),
        migrations.AddField(
            model_name='composemessageline',
            name='compose_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sms_app.composemessage'),
        ),
    ]
