# Generated by Django 5.2.7 on 2025-10-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0007_remove_composemessageline_sms_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='variable_type',
            field=models.CharField(choices=[('enable', 'Enable'), ('disable', 'Disable')], default='enable', max_length=10),
        ),
    ]
