# Generated by Django 5.2.7 on 2025-10-27 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0008_alter_messagetemplate_variable_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagetemplate',
            name='sender_id',
        ),
        migrations.RemoveField(
            model_name='messagetemplate',
            name='user_id',
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_app.sender'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
