# Generated by Django 5.2.8 on 2025-11-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0009_remove_messagetemplate_sender_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='available_credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credit',
            name='used_credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='credit',
            name='credits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
