# Generated by Django 5.2.8 on 2025-11-11 05:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0010_credit_available_credits_credit_used_credits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupHeader',
            fields=[
                ('group_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=255)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('attributes_1', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_2', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_3', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_4', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_5', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_6', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_7', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_8', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_9', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_10', models.CharField(blank=True, max_length=255, null=True)),
                ('create_by', models.CharField(blank=True, max_length=150, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated_by', models.CharField(blank=True, max_length=150, null=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_header',
                'ordering': ['group_id'],
            },
        ),
        migrations.CreateModel(
            name='GroupLine',
            fields=[
                ('group_line_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('attributes_1', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_2', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_3', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_4', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_5', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_6', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_7', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_8', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_9', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_10', models.CharField(blank=True, max_length=255, null=True)),
                ('create_by', models.CharField(blank=True, max_length=150, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated_by', models.CharField(blank=True, max_length=150, null=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sms_app.groupheader')),
            ],
            options={
                'db_table': 'group_line',
                'ordering': ['group_line_id'],
            },
        ),
    ]
