# Generated by Django 5.2.8 on 2025-11-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0011_groupheader_groupline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dlt_entity_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tier_level',
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(choices=[('Super Admin', 'Super Admin'), ('Support Admin', 'Support Admin'), ('Reseller', 'Reseller'), ('Client', 'Client')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_Account_type',
            field=models.CharField(choices=[('Support Admin', 'Support Admin'), ('Reseller', 'Reseller'), ('Client', 'Client')], max_length=50),
        ),
    ]
