# Generated by Django 5.2.8 on 2025-11-12 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0012_remove_user_company_status_remove_user_dlt_entity_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='tfa_number',
        ),
    ]
