# Generated by Django 5.2.8 on 2025-11-12 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0013_remove_company_tfa_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_Account_type',
        ),
    ]
