# Generated by Django 5.2.8 on 2025-11-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0014_remove_user_user_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='total_credits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
