# Generated by Django 5.2.8 on 2025-11-13 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0015_credit_total_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmppConnection',
            fields=[
                ('smpp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('connect_name', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_method', models.CharField(blank=True, max_length=255, null=True)),
                ('account_type', models.CharField(blank=True, max_length=255, null=True)),
                ('error_code_map', models.TextField(blank=True, null=True)),
                ('smpp_connect_status', models.CharField(blank=True, max_length=255, null=True)),
                ('ip', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('bind_type', models.CharField(blank=True, max_length=100, null=True)),
                ('tps', models.IntegerField(blank=True, null=True)),
                ('tr_trx_port', models.IntegerField(blank=True, null=True)),
                ('tx_sessions', models.IntegerField(blank=True, null=True)),
                ('rx_port', models.IntegerField(blank=True, null=True)),
                ('rx_sessions', models.IntegerField(blank=True, null=True)),
                ('system_type', models.CharField(blank=True, max_length=100, null=True)),
                ('dest_addr_ton', models.CharField(blank=True, max_length=100, null=True)),
                ('dest_addr_npi', models.CharField(blank=True, max_length=100, null=True)),
                ('source_addr_ton', models.CharField(blank=True, max_length=100, null=True)),
                ('source_addr_npi', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_report_timezone', models.CharField(blank=True, max_length=100, null=True)),
                ('override_delivery_time', models.CharField(blank=True, max_length=100, null=True)),
                ('support_message_validity', models.BooleanField(default=False)),
                ('date_format_in_dlr', models.CharField(blank=True, max_length=100, null=True)),
                ('modify_time_zone', models.CharField(blank=True, max_length=100, null=True)),
                ('dlt_enable', models.BooleanField(default=False)),
                ('dlt_telemarketer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('send_dlt_template_id', models.BooleanField(default=False)),
                ('reject_non_dlt_template_message', models.BooleanField(default=False)),
                ('dlt_entity_id_tag', models.CharField(blank=True, max_length=255, null=True)),
                ('dlt_template_id_tag', models.CharField(blank=True, max_length=255, null=True)),
                ('dlt_telemarketer_id_tag', models.CharField(blank=True, max_length=255, null=True)),
                ('dlt_telemarketer_tag_behaviour', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_1', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_2', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_3', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_4', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_5', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_6', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_7', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_8', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_9', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_10', models.CharField(blank=True, max_length=255, null=True)),
                ('create_by', models.CharField(blank=True, max_length=150, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated_by', models.CharField(blank=True, max_length=150, null=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='credit',
            name='credits',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
