# Generated by Django 5.2.8 on 2025-11-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0016_smppconnection_alter_credit_credits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smppconnection',
            options={'ordering': ['-last_updated_date'], 'verbose_name': 'SMPP Connection', 'verbose_name_plural': 'SMPP Connections'},
        ),
        migrations.AlterField(
            model_name='smppconnection',
            name='account_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='smppconnection',
            name='billing_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='smppconnection',
            name='bind_type',
            field=models.CharField(blank=True, choices=[('transmitter', 'Transmitter'), ('receiver', 'Receiver'), ('transceiver', 'Transceiver')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='smppconnection',
            name='date_format_in_dlr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='smppconnection',
            name='dest_addr_npi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smppconnection',
            name='dest_addr_ton',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smppconnection',
            name='modify_time_zone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='smppconnection',
            name='override_delivery_time',
            field=models.TimeField(blank=True, help_text='Override specific delivery time', null=True),
        ),
        migrations.AlterField(
            model_name='smppconnection',
            name='rx_port',
            field=models.IntegerField(blank=True, help_text='RX Port', null=True),
        ),
        migrations.AlterField(
            model_name='smppconnection',
            name='rx_sessions',
            field=models.IntegerField(blank=True, help_text='RX Sessions', null=True),
        ),
        migrations.AlterField(
            model_name='smppconnection',
            name='smpp_connect_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='smppconnection',
            name='source_addr_npi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smppconnection',
            name='source_addr_ton',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smppconnection',
            name='tps',
            field=models.IntegerField(blank=True, help_text='Transactions per second', null=True),
        ),
        migrations.AlterField(
            model_name='smppconnection',
            name='tr_trx_port',
            field=models.IntegerField(blank=True, help_text='TX/TRX Port', null=True),
        ),
        migrations.AlterField(
            model_name='smppconnection',
            name='tx_sessions',
            field=models.IntegerField(blank=True, help_text='TX Sessions', null=True),
        ),
        migrations.AlterModelTable(
            name='smppconnection',
            table='smpp_connection',
        ),
    ]
