# Generated by Django 5.2.8 on 2025-11-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0018_remove_smppconnection_override_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smppconnection',
            name='smpp_connect_status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
