# Generated by Django 5.2.8 on 2025-11-14 07:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0019_smppconnection_smpp_connect_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('rout_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('strategy', models.CharField(choices=[('Dedicated', 'Dedicated'), ('Percentage', 'Percentage'), ('Round-Robin', 'Round-Robin'), ('Priority', 'Priority')], default='Dedicated', max_length=50)),
                ('primary_connect', models.CharField(blank=True, max_length=255, null=True)),
                ('apply_rules', models.BooleanField(default=False)),
                ('message_retry', models.BooleanField(default=False)),
                ('reject_non_peid_messages', models.BooleanField(default=False)),
                ('attributes_1', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_2', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_3', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_4', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_5', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_6', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_7', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_8', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_9', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_10', models.CharField(blank=True, max_length=255, null=True)),
                ('create_by', models.CharField(blank=True, max_length=150, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated_by', models.CharField(blank=True, max_length=150, null=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
