# Generated by Django 5.2.8 on 2025-11-14 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0020_routing'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingMapping',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('attributes_1', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_2', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_3', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_4', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_5', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_6', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_7', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_8', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_9', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_10', models.CharField(blank=True, max_length=255, null=True)),
                ('create_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated_date', models.DateTimeField(blank=True, null=True)),
                ('routing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_app.routing')),
                ('smpp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_app.smppconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
