# Generated by Django 5.2.8 on 2025-11-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0021_routingmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='routingmapping',
            name='rout_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
