# Generated by Django 5.2.8 on 2025-11-17 08:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0022_routingmapping_rout_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routingmapping',
            name='smpp',
        ),
        migrations.CreateModel(
            name='RoutingMappingLine',
            fields=[
                ('rout_line_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('percentage_weight', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('attributes_1', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_2', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_3', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_4', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_5', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_6', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_7', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_8', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_9', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_10', models.CharField(blank=True, max_length=255, null=True)),
                ('create_by', models.CharField(blank=True, max_length=150, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated_by', models.CharField(blank=True, max_length=150, null=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('rout', models.ForeignKey(blank=True, db_column='rout_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routing_lines', to='sms_app.routing')),
                ('smpp', models.ForeignKey(blank=True, db_column='smpp_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routing_lines', to='sms_app.smppconnection')),
            ],
            options={
                'verbose_name': 'Routing Mapping Line',
                'verbose_name_plural': 'Routing Mapping Lines',
                'db_table': 'routing_mapping_line',
                'ordering': ['-last_updated_date'],
            },
        ),
    ]
