# Generated by Django 5.2.8 on 2025-11-17 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0023_remove_routingmapping_smpp_routingmappingline'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoutingMappingLine',
            new_name='RoutingLine',
        ),
    ]
