# Generated by Django 5.2.8 on 2025-11-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0024_rename_routingmappingline_routingline'),
    ]

    operations = [
        migrations.AddField(
            model_name='smppconnection',
            name='bind_status',
            field=models.CharField(choices=[('BOUND', 'BOUND'), ('UNBOUND', 'UNBOUND'), ('FAILED', 'FAILED'), ('RETRYING', 'RETRYING')], default='UNBOUND', max_length=20),
        ),
        migrations.AddField(
            model_name='smppconnection',
            name='connection_mode',
            field=models.CharField(choices=[('transmitter', 'Transmitter'), ('receiver', 'Receiver'), ('transceiver', 'Transceiver')], default='transceiver', max_length=20),
        ),
        migrations.AddField(
            model_name='smppconnection',
            name='keepalive_interval',
            field=models.IntegerField(default=30),
        ),
    ]
