# Generated by Django 5.2.8 on 2025-11-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0025_smppconnection_bind_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smppconnection',
            name='is_alive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smppconnection',
            name='last_bind_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smppconnection',
            name='last_enquire_link_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smppconnection',
            name='last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smppconnection',
            name='reconnect_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='smppconnection',
            name='rx_active_sessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='smppconnection',
            name='tx_active_sessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='smppconnection',
            name='uptime_seconds',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='smppconnection',
            name='bind_status',
            field=models.CharField(default='UNBOUND', max_length=20),
        ),
    ]
