# Generated by Django 5.2.8 on 2025-11-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0026_smppconnection_is_alive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smppconnection',
            name='window_size',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
