# Generated by Django 5.2.8 on 2025-11-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0027_smppconnection_window_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composemessageline',
            name='attributes_1',
            field=models.CharField(blank=True, max_length=2255, null=True),
        ),
        migrations.AlterField(
            model_name='composemessageline',
            name='attributes_10',
            field=models.CharField(blank=True, max_length=2255, null=True),
        ),
        migrations.AlterField(
            model_name='composemessageline',
            name='attributes_2',
            field=models.CharField(blank=True, max_length=2255, null=True),
        ),
        migrations.AlterField(
            model_name='composemessageline',
            name='attributes_3',
            field=models.CharField(blank=True, max_length=2255, null=True),
        ),
        migrations.AlterField(
            model_name='composemessageline',
            name='attributes_4',
            field=models.CharField(blank=True, max_length=2255, null=True),
        ),
        migrations.AlterField(
            model_name='composemessageline',
            name='attributes_5',
            field=models.CharField(blank=True, max_length=2255, null=True),
        ),
        migrations.AlterField(
            model_name='composemessageline',
            name='attributes_7',
            field=models.CharField(blank=True, max_length=2255, null=True),
        ),
        migrations.AlterField(
            model_name='composemessageline',
            name='attributes_8',
            field=models.CharField(blank=True, max_length=2255, null=True),
        ),
        migrations.AlterField(
            model_name='composemessageline',
            name='attributes_9',
            field=models.CharField(blank=True, max_length=2255, null=True),
        ),
        migrations.AlterField(
            model_name='composemessageline',
            name='masked_reason',
            field=models.CharField(blank=True, max_length=2255, null=True),
        ),
        migrations.AlterField(
            model_name='composemessageline',
            name='reason',
            field=models.CharField(blank=True, max_length=2255, null=True),
        ),
    ]
