# Generated by Django 5.2.8 on 2025-11-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0028_alter_composemessageline_attributes_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='composemessageline',
            name='sequence_number',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
