# Generated by Django 5.2.8 on 2025-12-09 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0029_composemessageline_sequence_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='credits',
            new_name='used_credit',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='available_credits',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='total_credits',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='used_credits',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='username',
        ),
        migrations.AddField(
            model_name='credit',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='credit',
            name='company',
            field=models.ForeignKey(blank=True, db_column='org_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_logs', to='sms_app.company'),
        ),
        migrations.AddField(
            model_name='credit',
            name='ending_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='credit',
            name='reference_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plan_type', models.CharField(blank=True, choices=[('Prepaid', 'Prepaid'), ('Postpaid', 'Postpaid')], max_length=50, null=True)),
                ('deduction_type', models.CharField(blank=True, choices=[('SMS', 'SMS'), ('Email', 'Email'), ('Voice', 'Voice'), ('Other', 'Other')], max_length=50, null=True)),
                ('action_type', models.CharField(blank=True, choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=50, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('attributes_1', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_2', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_3', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_4', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_5', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_6', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_7', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_8', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_9', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_10', models.CharField(blank=True, max_length=255, null=True)),
                ('create_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='org_id', on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='sms_app.company')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='credit',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='sms_app.wallet'),
        ),
    ]
