# Generated by Django 5.2.8 on 2025-12-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0030_rename_credits_credit_used_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='deduction_type',
            field=models.CharField(blank=True, choices=[('SUBMITTION', 'SUBMITTION'), ('DELIVERED', 'DELIVERED')], max_length=50, null=True),
        ),
    ]
