# Generated by Django 5.2.8 on 2025-12-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0031_alter_wallet_deduction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='deduction_type',
            field=models.CharField(blank=True, choices=[('SUBMISSION', 'SUBMISSION'), ('DELIVERED', 'DELIVERED')], max_length=50, null=True),
        ),
    ]
