# Generated by Django 5.2.8 on 2025-12-11 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0032_alter_wallet_deduction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credit',
            name='from_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_credits', to='sms_app.wallet'),
        ),
        migrations.AddField(
            model_name='credit',
            name='starting_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='credit',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='COMPLETED', max_length=20),
        ),
        migrations.AddField(
            model_name='credit',
            name='to_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_credits', to='sms_app.wallet'),
        ),
        migrations.AddField(
            model_name='credit',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('WALLET_CREATION', 'Wallet Creation'), ('BALANCE_UPDATE', 'Balance Update'), ('DEDUCTION', 'Deduction'), ('REFUND', 'Refund'), ('WALLET_TRANSFER', 'Wallet Transfer')], max_length=50, null=True),
        ),
    ]
