# Generated by Django 5.2.8 on 2026-01-30 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0033_credit_description_credit_from_wallet_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'ordering': ['-created_date'], 'verbose_name': 'Credit Transaction', 'verbose_name_plural': 'Credit Transactions'},
        ),
        migrations.CreateModel(
            name='SmppHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], max_length=3)),
                ('entity_id', models.CharField(blank=True, max_length=100, null=True)),
                ('template_id', models.CharField(blank=True, max_length=100, null=True)),
                ('provider', models.CharField(blank=True, max_length=100, null=True)),
                ('packet_tm_id', models.CharField(blank=True, max_length=100, null=True)),
                ('hash_key', models.CharField(blank=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smpp_hashes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
