# Generated by Django 5.2.8 on 2026-01-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0034_alter_credit_options_smpphash'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='composemessageline',
            index=models.Index(fields=['message_id'], name='sms_app_com_message_0322b8_idx'),
        ),
        migrations.AddIndex(
            model_name='composemessageline',
            index=models.Index(fields=['status'], name='sms_app_com_status_a2d5e3_idx'),
        ),
        migrations.AddIndex(
            model_name='composemessageline',
            index=models.Index(fields=['submit_time'], name='sms_app_com_submit__ca9dab_idx'),
        ),
    ]
