# Generated by Django 5.2.8 on 2026-02-03 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0035_composemessageline_sms_app_com_message_0322b8_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTable',
            fields=[
                ('hash_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('pe_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tmid', models.CharField(blank=True, max_length=100, null=True)),
                ('hash_value', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('attribute1', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute2', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute3', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute4', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute5', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute6', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute7', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute8', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute9', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute10', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('connection', models.ForeignKey(blank=True, db_column='connection_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_app.smppconnection')),
                ('sender', models.ForeignKey(blank=True, db_column='sender_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_app.sender')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hash Table',
                'verbose_name_plural': 'Hash Tables',
                'db_table': 'hash_table',
            },
        ),
    ]
