# Generated by Django 5.2.8 on 2026-02-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0036_hashtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtable',
            name='type',
            field=models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF'), ('HASH', 'HASH'), ('PACKET_TM', 'PACKET_TM')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='SmppHash',
        ),
    ]
