# Generated by Django 5.2.8 on 2026-02-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0037_alter_hashtable_type_delete_smpphash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtable',
            name='type',
            field=models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF'), ('PROVIDE_TM', 'PROVIDE_TM'), ('PACKET_TM', 'PACKET_TM')], max_length=10, null=True),
        ),
    ]
