# Generated by Django 5.2.8 on 2026-02-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0038_alter_hashtable_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composemessage',
            name='attributes_1',
            field=models.CharField(blank=True, max_length=2255, null=True),
        ),
        migrations.AlterField(
            model_name='composemessage',
            name='attributes_10',
            field=models.CharField(blank=True, max_length=2255, null=True),
        ),
        migrations.AlterField(
            model_name='composemessage',
            name='attributes_2',
            field=models.CharField(blank=True, max_length=2255, null=True),
        ),
        migrations.AlterField(
            model_name='composemessage',
            name='attributes_3',
            field=models.CharField(blank=True, max_length=2525, null=True),
        ),
        migrations.AlterField(
            model_name='composemessage',
            name='attributes_4',
            field=models.CharField(blank=True, max_length=2552, null=True),
        ),
        migrations.AlterField(
            model_name='composemessage',
            name='attributes_5',
            field=models.CharField(blank=True, max_length=2255, null=True),
        ),
        migrations.AlterField(
            model_name='composemessage',
            name='attributes_6',
            field=models.CharField(blank=True, max_length=2255, null=True),
        ),
        migrations.AlterField(
            model_name='composemessage',
            name='attributes_7',
            field=models.CharField(blank=True, max_length=2255, null=True),
        ),
        migrations.AlterField(
            model_name='composemessage',
            name='attributes_8',
            field=models.CharField(blank=True, max_length=2255, null=True),
        ),
        migrations.AlterField(
            model_name='composemessage',
            name='attributes_9',
            field=models.CharField(blank=True, max_length=2255, null=True),
        ),
    ]
