# Generated by Django 5.2.8 on 2026-03-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0039_alter_composemessage_attributes_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='composemessage',
            name='status',
            field=models.CharField(blank=True, default='PENDING', max_length=50, null=True),
        ),
    ]
