# Generated by Django 5.2.8 on 2026-03-31 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0042_composemessage_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composemessage',
            name='status',
        ),
    ]
